apiVersion: apps/v1
kind: Deployment
metadata:
  name: godrop
  labels:
    app: godrop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: godrop
  template:
    metadata:
      labels:
        app: godrop
    spec:
      containers:
        - name: godrop
          image: godrop:local
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: godrop-config
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: demo
              mountPath: /srv/godrop
              readOnly: true
      volumes:
        - name: demo
          hostPath:
            path: /opt/godrop
            type: Directory
