apiVersion: v1
kind: Service
metadata:
  name: godrop
  labels:
    app: godrop
spec:
  type: ClusterIP
  selector:
    app: godrop
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
