apiVersion: v1
kind: PersistentVolume
metadata:
  name: godrop-data
  labels:
    app: godrop
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /opt/godrop
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - godrop-control-plane
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: godrop-data
  labels:
    app: godrop
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  storageClassName: ""
  volumeName: godrop-data
